title = "rSQL"
gitRepoUrl = "https://github.com/your-org-name/rsql" 

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.png"

organizationName = "rSQL"
projectName = "rSQL"
url = "https://o.github.io"
baseUrl = "/rsql"
tagline = "SQL-like Operations for Roblox Development"

[footer]
style = "dark"
copyright = "Copyright © ${new Date().getFullYear()} Your Organization. Built with Moonwave and Docusaurus"

[[footer.links]]
title = "Resources"

[[footer.links.items]]
label = "Documentation"
href = "/docs"


apiCategories = [
    "constructor",
    "utility",
    "queries",
    "transactions"
]

[home]
enabled = true
includeReadme = false