title = "rSQL"
gitRepoUrl = "https://github.com/rustyspottedcatt/rSQL" 
gitSourceBranch = "main"
changelog = true
autoSectionPath = "src"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
url = "https://rustyspottedcatt.github.io"
baseUrl = "/rSQL/"
favicon = "/favicon.png"

[footer]
style = "dark"
copyright = "Copyright © 2024 rSQL. Built with Moonwave and Docusaurus."

[home]
enabled = true
includeReadme = false