title = "rSQL"
gitRepoUrl = "https://github.com/rustyspottedcatt/rSQL" 

gitSourceBranch = "main"
changelog = true
autoSectionPath = "packages"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.png"

[footer]
style = "dark"
copyright = "Copyright © ${new Date().getFullYear()} Your Organization. Built with Moonwave and Docusaurus"

[home]
enabled = true
includeReadme = false